SET FOREIGN_KEY_CHECKS = 0;
drop table Categoria_Utilizador;
drop table Utilizador;
drop table FormatoQuestoes;
drop table Resposta;
drop table Questao ;
drop table Quiz ;
drop table Modulo;
drop table AcaoFormativa;
SET FOREIGN_KEY_CHECKS = 1;
